// Associe un nom d'équipe (nation) à un drapeau emoji. Fallback : ⚽.
const FLAGS: Record<string, string> = {
  'france': '🇫🇷',
  'angleterre': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'england': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'irlande du nord': '🇬🇧',
  'northern ireland': '🇬🇧',
  'irlande': '🇮🇪',
  'ireland': '🇮🇪',
  'ecosse': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'pays de galles': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'espagne': '🇪🇸',
  'spain': '🇪🇸',
  'allemagne': '🇩🇪',
  'germany': '🇩🇪',
  'italie': '🇮🇹',
  'italy': '🇮🇹',
  'portugal': '🇵🇹',
  'belgique': '🇧🇪',
  'belgium': '🇧🇪',
  'pays-bas': '🇳🇱',
  'netherlands': '🇳🇱',
  'croatie': '🇭🇷',
  'croatia': '🇭🇷',
  'bresil': '🇧🇷',
  'brésil': '🇧🇷',
  'brazil': '🇧🇷',
  'argentine': '🇦🇷',
  'argentina': '🇦🇷',
  'maroc': '🇲🇦',
  'morocco': '🇲🇦',
  'suisse': '🇨🇭',
  'switzerland': '🇨🇭',
  'pologne': '🇵🇱',
  'poland': '🇵🇱',
  'danemark': '🇩🇰',
  'denmark': '🇩🇰',
  'autriche': '🇦🇹',
  'austria': '🇦🇹',
  'ukraine': '🇺🇦',
  'turquie': '🇹🇷',
  'turkey': '🇹🇷',
  'usa': '🇺🇸',
  'etats-unis': '🇺🇸',
};

export function flagFor(team: string): string {
  if (!team) return '⚽';
  return FLAGS[team.trim().toLowerCase()] || '⚽';
}
